# Generated by Django 3.2.7 on 2021-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_categorymodel_stylename'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='stylename',
        ),
    ]
