# Generated by Django 3.2.7 on 2021-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20211002_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
