# Generated by Django 3.2.7 on 2021-10-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_categorymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='name',
        ),
    ]
