# Generated by Django 3.2.7 on 2021-10-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_categorymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylemodel',
            name='style_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='settings.categorymodel'),
            preserve_default=False,
        ),
    ]
