# Generated by Django 3.2.7 on 2021-10-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_stylemodel_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='settings.stylemodel'),
            preserve_default=False,
        ),
    ]
