# Generated by Django 3.2.7 on 2021-10-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_categorymodel_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.categorymodel'),
        ),
    ]
