# Generated by Django 3.2.7 on 2021-10-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_categorymodel_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category_id',
        ),
    ]
