# Generated by Django 3.2.7 on 2021-10-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_remove_categorymodel_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylemodel',
            old_name='style_id',
            new_name='post_id',
        ),
    ]
