# Generated by Django 3.2.7 on 2021-10-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_rename_style_id_stylemodel_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylemodel',
            old_name='post_id',
            new_name='style_id',
        ),
    ]
