# Generated by Django 3.2.7 on 2021-10-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20211005_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='style_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='settings.navbarmodel'),
            preserve_default=False,
        ),
    ]
