# Generated by Django 3.2.7 on 2021-10-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_categorymodel_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmodel',
            name='navbar_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='settings.navbarmodel'),
            preserve_default=False,
        ),
    ]
