# Generated by Django 3.2.7 on 2021-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_navbarmodel_navbar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='style_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='navbarmodel',
            name='navbar_id',
            field=models.IntegerField(),
        ),
    ]
