# Generated by Django 3.2.7 on 2021-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_auto_20211006_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category1',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
