# Generated by Django 3.2.8 on 2021-10-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_auto_20211009_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarmodel',
            name='category_id',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='settings.navbarmodel'),
            preserve_default=False,
        ),
    ]
