# Generated by Django 3.2.8 on 2021-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_auto_20211009_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='category_id',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_id',
            field=models.ManyToManyField(to='settings.NavbarModel'),
        ),
    ]
