# Generated by Django 3.2.8 on 2021-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_auto_20211009_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
