# Generated by Django 3.2.8 on 2021-10-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_alter_navbarmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmodel',
            name='category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navbarmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
