# Generated by Django 3.2.8 on 2021-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_auto_20211012_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
