# Generated by Django 3.2.8 on 2021-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_auto_20211013_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='background_image',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
