# Generated by Django 3.2.8 on 2021-10-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_auto_20211013_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
