# Generated by Django 3.2.8 on 2021-10-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_auto_20211013_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='post_id',
        ),
    ]
