# Generated by Django 3.2.8 on 2021-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_remove_imagemodel_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
