# Generated by Django 3.2.8 on 2021-10-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_auto_20211013_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
