# Generated by Django 3.2.8 on 2021-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='subcategory',
            field=models.BooleanField(default=False),
        ),
    ]
