# Generated by Django 3.2.8 on 2021-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_categorymodel_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory_id',
            field=models.ManyToManyField(to='settings.CategoryModel'),
        ),
    ]
