# Generated by Django 3.2.8 on 2021-10-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_products_subcategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='url',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
