# Generated by Django 3.2.8 on 2021-10-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0043_auto_20211018_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.ManyToManyField(to='settings.NavbarModel'),
        ),
    ]
