# Generated by Django 3.2.8 on 2021-10-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0045_auto_20211018_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_id',
        ),
    ]
