# Generated by Django 3.2.8 on 2021-10-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0046_remove_products_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subcategory_id',
        ),
    ]
