# Generated by Django 3.2.8 on 2021-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0047_auto_20211020_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
