# Generated by Django 3.2.8 on 2021-10-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0048_auto_20211020_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
