# Generated by Django 3.2.8 on 2021-10-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0051_products_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_id',
        ),
    ]
