# Generated by Django 3.2.8 on 2021-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0055_products_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='delete_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
