# Generated by Django 3.2.8 on 2021-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0056_auto_20211023_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='and_more',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('and_more', models.CharField(blank=True, max_length=100, null=True)),
                ('and_more_id', models.ManyToManyField(blank=True, null=True, to='settings.CategoryModel')),
            ],
        ),
    ]
