# Generated by Django 3.2.8 on 2021-10-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0057_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='and_more',
        ),
    ]
