# Generated by Django 3.2.8 on 2021-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0058_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmodel',
            name='slice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
