# Generated by Django 3.2.8 on 2021-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0059_navbarmodel_slice'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_folder'),
        ),
    ]
