# Generated by Django 3.2.8 on 2021-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0060_auto_20211024_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='sale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
