# Generated by Django 3.2.8 on 2021-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0061_auto_20211024_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images_folder'),
        ),
    ]
