# Generated by Django 3.2.8 on 2021-10-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0062_auto_20211024_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(blank=True, max_length=100, null=True)),
                ('image_text', models.CharField(blank=True, max_length=100, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images_folder')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_text',
        ),
    ]
