# Generated by Django 3.2.8 on 2021-10-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0063_auto_20211024_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarmodel',
            name='slice',
        ),
    ]
