# Generated by Django 3.2.9 on 2021-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0064_auto_20211102_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message',
            field=models.CharField(default=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
