# Generated by Django 3.2.8 on 2021-11-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0065_auto_20211102_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_id',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_id',
            field=models.ManyToManyField(to='settings.Products'),
        ),
    ]
