# Generated by Django 3.2.8 on 2021-11-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0065_creatormodel'),
        ('settings', '0066_creatormodel'),
    ]

    operations = [
    ]
