# Generated by Django 3.2.8 on 2021-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0067_merge_0065_creatormodel_0066_creatormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatormodel',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
