# Generated by Django 3.2.8 on 2021-11-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0064_auto_20211102_0658'),
        ('settings', '0067_remove_imagemodel_image_id'),
    ]

    operations = [
    ]
