# Generated by Django 3.2.8 on 2021-11-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0069_clientbrandmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('adress', models.CharField(blank=True, max_length=45, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('wdigets', models.ImageField(blank=True, null=True, upload_to='images_folder')),
                ('widgets_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
